apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-cfg
data:
  core-site.xml: |-
    <configuration>
        <property>
            <name>fs.s3a.access.key</name>
            <value></value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value></value>
        </property>
        <property>
            <name>fs.s3a.connection.ssl.enabled</name>
           <value>false</value>
        </property>
        <property>
            <name>fs.s3a.impl</name>
            <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>http://kr.objectstorage.ncloud.com</value>
        </property>
        <property>
            <name>fs.defaultFS</name>
            <value>s3a://testtesttesttest</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
        <property>
            <name>fs.s3a.fast.upload</name>
            <value>true</value>
        </property>
    </configuration>
  metastore-site.xml: |-
    <configuration>
       <property>
          <name>metastore.task.threads.always</name>
          <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>
       </property>
       <property>
          <name>metastore.expression.proxy</name>
          <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
       </property>
       <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          <value>com.mysql.jdbc.Driver</value>
       </property>
       <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>jdbc:mysql://mysql-service.trino.svc.cluster.local:3306/metastore_db?useSSL=false&amp;allowPublicKeyRetrieval=true</value>
       </property>
       <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>root</value>
       </property>
       <property>
          <name>javax.jdo.option.ConnectionPassword</name>
          <value>910506</value>
       </property>
       <property>
          <name>metastore.warehouse.dir</name>
          <value>s3a://testtesttesttest/hive-meta/</value>
       </property>
       <property>
          <name>metastore.thrift.port</name>
          <value>9083</value>
       </property>
    </configuration>